# Generated by Django 5.0.2 on 2024-03-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techExApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
